In [1]:
#class imbalnced -- when one class has higher percentage

In [3]:
#handle :
#1 : oversampling
#2 : undersampling
#3 : SMOTE

In [4]:
import pandas as pd
import numpy as np

In [6]:
np.random.seed(1) #for reproducibility of result

np.random.seed(1) -- means if we genrate random no at any time it will be saME

In [7]:
no_sample = 1000
class_0_ratio = 0.9
no_class_0 = int(no_sample * class_0_ratio)
no_class_1 = no_sample - no_class_0

In [8]:
no_class_0

900

In [9]:
no_class_1

100

In [12]:
class_o = {'feature1': np.random.normal(0,1,no_class_0)}

In [13]:
class_o = {'feature2': np.random.normal(0,1,no_class_0),'target':[0]*no_class_0}

In [14]:
class_0 = pd.DataFrame(class_o)

In [16]:
class_0

     feature2  target
0   -0.446699       0
1    0.204377       0
2    0.612233       0
3    0.744885       0
4   -0.036281       0
..        ...     ...
895  0.833679       0
896  2.160456       0
897  1.998992       0
898  0.764041       0
899  1.687255       0

[900 rows x 2 columns]

In [20]:
class_1 = pd.DataFrame({'feature1': np.random.normal(3,1,no_class_1)
,'feature2': np.random.normal(0,1,no_class_1),'target':[1]*no_class_1})

In [21]:
class_1

    feature1  feature2  target
0   3.489517  0.482598       1
1   3.238796 -1.105432       1
2   2.551888  0.420755       1
3   2.389205  1.616794       1
4   0.970055 -0.883771       1
..       ...       ...     ...
95  3.268527 -0.708655       1
96  2.844950 -0.872502       1
97  5.112622 -1.093790       1
98  3.256079 -1.534700       1
99  2.793239 -0.851262       1

[100 rows x 3 columns]

In [24]:
df = pd.concat([class_0,class_1]).reset_index(drop=True)

In [25]:
df.target.value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [26]:
df

     feature2  target  feature1
0   -0.446699       0       NaN
1    0.204377       0       NaN
2    0.612233       0       NaN
3    0.744885       0       NaN
4   -0.036281       0       NaN
..        ...     ...       ...
995 -0.708655       1  3.268527
996 -0.872502       1  2.844950
997 -1.093790       1  5.112622
998 -1.534700       1  3.256079
999 -0.851262       1  2.793239

[1000 rows x 3 columns]

In [27]:
#upsampling

In [28]:
df_minority = df[df.target == 1]
df_majority = df[df.target == 0]

In [29]:
df_majority

     feature2  target  feature1
0   -0.446699       0       NaN
1    0.204377       0       NaN
2    0.612233       0       NaN
3    0.744885       0       NaN
4   -0.036281       0       NaN
..        ...     ...       ...
895  0.833679       0       NaN
896  2.160456       0       NaN
897  1.998992       0       NaN
898  0.764041       0       NaN
899  1.687255       0       NaN

[900 rows x 3 columns]

In [30]:
df_minority

     feature2  target  feature1
900  0.482598       1  3.489517
901 -1.105432       1  3.238796
902  0.420755       1  2.551888
903  1.616794       1  2.389205
904 -0.883771       1  0.970055
..        ...     ...       ...
995 -0.708655       1  3.268527
996 -0.872502       1  2.844950
997 -1.093790       1  5.112622
998 -1.534700       1  3.256079
999 -0.851262       1  2.793239

[100 rows x 3 columns]

In [31]:
#replace --- if replace is true , it means data point can be repeated

In [32]:
from sklearn.utils import resample

In [35]:
df_minority_upsampled = resample(df_minority,replace=True , n_samples=len(df_majority),random_state=1)

In [36]:
df_minority_upsampled

     feature2  target  feature1
937 -0.324332       1  4.310159
912 -0.232603       1  4.496995
972  0.681402       1  3.033929
909 -1.044998       1  2.213597
975  0.625218       1  4.054868
..        ...     ...       ...
936  2.208662       1  2.154805
998 -1.534700       1  3.256079
901 -1.105432       1  3.238796
932  0.919447       1  3.666244
930  2.421589       1  3.310624

[900 rows x 3 columns]

In [37]:
df_minority_upsampled.shape

(900, 3)

In [39]:
df_upsampled = pd.concat([df_majority,df_minority_upsampled])

In [40]:
df_upsampled

     feature2  target  feature1
0   -0.446699       0       NaN
1    0.204377       0       NaN
2    0.612233       0       NaN
3    0.744885       0       NaN
4   -0.036281       0       NaN
..        ...     ...       ...
936  2.208662       1  2.154805
998 -1.534700       1  3.256079
901 -1.105432       1  3.238796
932  0.919447       1  3.666244
930  2.421589       1  3.310624

[1800 rows x 3 columns]

In [41]:
df_upsampled.target.value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [42]:
#Down Sampling

In [44]:
df_minority

     feature2  target  feature1
900  0.482598       1  3.489517
901 -1.105432       1  3.238796
902  0.420755       1  2.551888
903  1.616794       1  2.389205
904 -0.883771       1  0.970055
..        ...     ...       ...
995 -0.708655       1  3.268527
996 -0.872502       1  2.844950
997 -1.093790       1  5.112622
998 -1.534700       1  3.256079
999 -0.851262       1  2.793239

[100 rows x 3 columns]

In [45]:
df_majority

     feature2  target  feature1
0   -0.446699       0       NaN
1    0.204377       0       NaN
2    0.612233       0       NaN
3    0.744885       0       NaN
4   -0.036281       0       NaN
..        ...     ...       ...
895  0.833679       0       NaN
896  2.160456       0       NaN
897  1.998992       0       NaN
898  0.764041       0       NaN
899  1.687255       0       NaN

[900 rows x 3 columns]

In [46]:
resample(df_majority,replace=False , n_samples=len(df_minority),random_state=1)

     feature2  target  feature1
860  0.872579       0       NaN
880  1.835870       0       NaN
874  0.146532       0       NaN
780 -0.859827       0       NaN
525  0.320971       0       NaN
..        ...     ...       ...
494  2.711950       0       NaN
255  0.522655       0       NaN
672  0.683356       0       NaN
481 -0.800787       0       NaN
838 -0.698571       0       NaN

[100 rows x 3 columns]

In [47]:
df_majority_downsampled = resample(df_majority,replace=False , n_samples=len(df_minority),random_state=1)

In [50]:
df_downsampled = pd.concat([df_minority,df_majority_downsampled])

In [51]:
df_downsampled

     feature2  target  feature1
900  0.482598       1  3.489517
901 -1.105432       1  3.238796
902  0.420755       1  2.551888
903  1.616794       1  2.389205
904 -0.883771       1  0.970055
..        ...     ...       ...
494  2.711950       0       NaN
255  0.522655       0       NaN
672  0.683356       0       NaN
481 -0.800787       0       NaN
838 -0.698571       0       NaN

[200 rows x 3 columns]

In [52]:
df_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64

In [53]:
#SMOTE -- SYNTHETIC MINORITY OVERSAMPLING TECHNIQUE

In [54]:
from sklearn.datasets import make_classification

In [65]:
make_classification(n_samples=1000,n_redundant=0, n_features=2,n_clusters_per_class =1,weights=[0.90])

(array([[ 1.26471893,  1.01152664],
        [-1.60006265,  0.53789328],
        [ 1.46628371, -0.25226574],
        ...,
        [-0.83793734,  0.43129889],
        [-1.12281773,  0.9511746 ],
        [-0.90724139,  0.66776276]]),
 array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 0]))